services:
    traefik:
        image: traefik:v3.6
        container_name: traefik
        network_mode: 'host'
        userns_mode: 'host'
        # ports: # if switching back from host networking
        #     - "80:80"
        #     - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.yml:/etc/traefik/traefik.yml
            - ./dynamic.yml:/etc/traefik/dynamic.yml
            - ./certs/dev.pem:/etc/certs/dev.pem:ro
            - ./certs/dev-key.pem:/etc/certs/dev-key.pem:ro
        restart: unless-stopped
        # networks:
        #     - web_dev
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.enable=false" # dashboard router is in dynamic.yml (api@internal)

    mailcatcher:
        image: schickling/mailcatcher
        container_name: mailcatcher
        # ports:
        #     - "1080:1080"
        #     - "1025:1025"
        # environment:
        #     SMTP_PORT: 25
        #     HTTP_PORT: 80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.docker.localhost`)"
            - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
            - "traefik.http.routers.mailcatcher.entrypoints=websecure"
        networks:
            - web_dev
        restart: unless-stopped

    # kanboard:
    #   image: kanboard/kanboard:latest
    #   volumes:
    #     - kanboard_data:/var/www/app/data
    #     - kanboard_plugins:/var/www/app/plugins
    #     # - kanboard_ssl:/etc/nginx/ssl
    #   labels:
    #     - "traefik.enable=true"
    #     - "traefik.http.routers.kanboard.rule=Host(`kanboard.docker.localhost`)"
    #     - "traefik.http.routers.kanboard.entrypoints=websecure"
    #     - "traefik.http.services.kanboard.loadbalancer.server.port=80"
    #   networks:
    #     - web_dev
    #   restart: unless-stopped

    # portainer:
    #     image: portainer/portainer-ce:latest
    #     container_name: portainer
    #     restart: always
    #     # ports:
    #     #     - "9000:9000"
    #     #     - "9443:9443"
    #     environment:
    #         - http_port=9000
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - portainer_data:/data
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.portainer.rule=Host(`portainer.docker.localhost`)"
    #         - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    #         - "traefik.http.routers.portainer.entrypoints=websecure"
    #     networks:
    #         - web_dev

networks:
    web_dev:
        external: true

# volumes:
#     kanboard_data:
#     kanboard_plugins:
#     kanboard_ssl:
#     portainer_data:
